### ISSUE TITLE
Team logo upload

### ISSUE THREAD

**Issue by NevErdiEkilLeR** [osamhack2020/WEB_WebbasedAutomatedMeasurementService_Doyouhaveameasurementproblem#1]
![로고_DyhaMP](https://user-images.githubusercontent.com/5003195/95662227-58dc3000-0b70-11eb-8727-95f99797a783.jpg)

**Comment by ginami0129** [comment]
팀원들 전부 확인한 부분이니 이슈 닫겠습니다
